version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: decode google-services.json
          command:
            echo "$GOOGLE_SERVICE_JSON" | base64 --decode --ignore-garbage > ./app/google-services.json
      - run:
          name: decode jks file
          command:
            echo "$KEYSTORE_BASE_64 | base 64 --decode --ignore-grabage > ~/release.jks

      - run:
          name: Export version code
          command: echo 'export ORG_GRADLE_PROJECT_VERSION_CODE="$CIRCLE_BUILD_NUM"' >> $BASH_ENV
      - run:
          name: generate local.properties
          command:
              echo "push_to_fcm.server_base_url=${PUSH_TO_FCM_SERVER_BASE_URL}" >> ./local.properties
              echo "push_to_fcm.public_key=${PUSH_TO_FCM_PUBLIC_KEY}" >> ./local.properties
              echo "push_to_fcm.auth=${PUSH_TO_FCM_AUTH}" >> ./local.properties

      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease

  release-and-publish:
    executor:
      name: android/android-machine

    steps:
      - checkout
      - run:
          name: decode jks file
          command:
            echo "$KEYSTORE_BASE_64 | base 64 --decode --ignore-grabage > ~/release.jks

      - run:
          name: Export version code
          command: echo 'export ORG_GRADLE_PROJECT_VERSION_CODE="$CIRCLE_BUILD_NUM"' >> $BASH_ENV
      - run:
          name: Assemble release build and publish
          command: |
            ./gradlew publishBundle \
              -Pandroid.injected.signing.store.file=~/release.jks \
              -Pandroid.injected.signing.store.password=$STORE_PASSWORD \
              -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
              -Pandroid.injected.signing.key.password=$KEY_PASSWORD


workflows:
  sample:
    jobs:
      - build-and-test
  ci-and-deploy:
    jobs:
      - build-and-test
      - release-and-publish
        requires:
          - build-and-test



