name: Go Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.2
      uses: actions/setup-go@v2
      with:
        go-version: 1.2

    - name: Install Dependencies
      run: go get -v -t -d ./...
      working-directory: ./push-to-fcm

    - name: Test
      run: go test ./...
      working-directory: ./push-to-fcm
